### ISSUE TITLE
ExAd_HACKING_MAX_DISTANCE Not Respected

### ISSUE THREAD

**Issue by OmenLW** [Bjanski/ExAd#36] opened 2016-05-09 17:33 UTC
You can set ExAd_HACKING_MAX_DISTANCE = 25, start a hack, run 150m out and the hacking continues.

**Comment by Bjanski** [comment] 2016-05-09 18:51
@OmenLW Could you elaborate more. The script is working for everyone else, I've tried to recreate the issue but everything works for me. The timer stops and the hack is waiting for a player to get into the area again.

Do you have any other mods installed?
Which scripts are you running?

Do you get any errors in the server logs?

When you say it continues, do mean it doesn't abort/disappear? 
It shouldn't disappear, It should only pause the countdown.

**Comment by Bjanski** [comment] 2016-05-10 15:52
@OmenLW  Can't reproduce the issue, need more intel.

**Comment by Bjanski** [comment] 2016-05-14 20:49
Closing the issue since no additional feedback was given and I couldn't replicate the issue.

**Closed by Bjanski** 2016-05-14 20:49 UTC
Labels: Hacking, Under review
